#!/usr/bin/env bash
# Displays the current directory in list format
#   Only displays part of the name after first dash 

for file in *; do
    [[ "$file" == .* ]] && continue
    part="${file#*-}"
    if [[ "$file" != "$part" ]]; then
        echo "$part"
    fi

done
