#!/usr/bin/env bash
# Displays the current directory in list format
#   Only displays part of the name after first dash 

for file in *; do
    if [[ -f "$file" || -d "$file" ]]; then
        if [[ "$file" == *-* ]]; then
            echo "${file#*-}"
        else
            echo "$file"
        fi
    fi
done
